---
# Create required directory structure

- name: Create Consul configuration directory
  file:
    path: /etc/consul.d
    state: directory
    owner: consul
    group: consul
    mode: '0755'

- name: Create Consul data directory
  file:
    path: /opt/consul
    state: directory
    owner: consul
    group: consul
    mode: '0755'

- name: Create Consul log directory
  file:
    path: /var/log/consul
    state: directory
    owner: consul
    group: consul
    mode: '0755'

- name: Create Consul-Template directory
  file:
    path: /etc/consul-template
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create Docker directory
  file:
    path: /root/docker
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create doctl config directory
  file:
    path: /root/.config/doctl
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create Alloy directory
  file:
    path: /etc/alloy
    state: directory
    owner: root
    group: root
    mode: '0755'
